spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: exercices
      username: root
      password: "EXO11hjkl"
      authentication-database: admin

logging:
  level:
    org.springframework.data.mongodb: DEBUG